"""
Main Orchestrator for Agentic RAG System
========================================

This module implements the main LangGraph-based orchestrator that replaces
hardcoded if-else conditions with intelligent decision making using LLM.

Architecture:
- AGENTS: Components that make decisions using LLM calls (QueryOrchestrator)
- TOOLS: Simple data retrieval functions without decision making (PersonalDataTool, etc.)

LangGraph Best Practices:
- Agents handle reasoning, planning, and LLM interactions
- Tools handle pure data retrieval and external API calls
- Clear separation ensures proper workflow and prevents circular dependencies
"""

import asyncio
import logging
import time
import os
from typing import TypedDict, List, Optional, Dict, Any, Annotated
from citra_llm import get_default_model
from dataclasses import dataclass, field
from langgraph.graph import StateGraph, END
from enum import Enum
import uuid
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

from .source_provider import get_source_provider, SourceConfig

from .simplified_planner import SimplifiedStrategyPlanner  # New intelligent planner
# from .agents import MultiHopAgent  # REMOVED: MultiHopAgent not implemented
from .tools import RETRIEVAL_TOOLS
from .context_merger import ContextMerger

# Structured data services — used by other UI paths (presentation, printable, composer).
# Chat UI now gets structured data exclusively via SaaSDataTool in source_provider.

logger = logging.getLogger(__name__)

# ====================================================================================================
# Core Enums and Dataclasses for Agentic RAG
# ====================================================================================================
# Note: Previously in planner.py, moved here since orchestrator is the primary consumer

class RetrievalStrategy(Enum):
    """Available retrieval strategies for the orchestrator"""
    PERSONAL_ONLY = "personal_only"
    ENTERPRISE = "enterprise"   # Enterprise vault + remote Citra instances
    COMBINED = "combined"  # Multiple strategies needed

@dataclass
class SubQuery:
    """Individual sub-query generated by SimplifiedStrategyPlanner"""
    query_text: str
    priority: int = 1  # 1 = highest priority
    reasoning: str = ""

@dataclass 
class QueryIntent:
    """Query intent analysis result from SimplifiedStrategyPlanner"""
    needs_decomposition: bool = False
    sub_queries: List[SubQuery] = field(default_factory=list)
    original_complexity: str = "simple"  # simple, moderate, complex
    requires_project_data: bool = False  # For project management queries
    # NOTE: SaaS data now fetched via Milvus `saas` collection semantic search
    # No need for live_data routing - SaaSDataTool handles it automatically
    
    # Query enhancement tracking
    original_query: str = ""  # Original user query
    enhanced_query: str = ""  # Query with entity context injected
    query_was_enhanced: bool = False  # Whether enhancement was applied
    
    # Legacy fields for backward compatibility
    requires_personal_context: bool = False
    reasoning: str = ""
    decomposed_queries: List[str] = field(default_factory=list)
    confidence_score: float = 0.8
    
    # Enhanced fields for retrieval
    simple_retrieval_parts: List[str] = field(default_factory=list)

# ====================================================================================================

class QueryState(TypedDict):
    """State for the query processing graph"""
    # Input parameters
    query: str
    original_query: Optional[str]  # Original query before enrichment (for display)
    user_id: str
    user_email: Optional[str]  # User email for credit tracking
    vault_id: Optional[str]  # Vault ID for project management queries
    use_personal_data: bool
    conversation_history: List[Dict[str, Any]]
    multimodal_attachments: Optional[List[Dict[str, Any]]]
    persona_data: Optional[Dict[str, Any]]  # User persona data from query API
    enable_internet_search: bool  # Internet search toggle from UI
    force_internet: Optional[bool]  # Bypass adaptive gating; require internet_search this turn
    legal_collection_ids: Optional[List[str]]  # LLM collection IDs from legal filters

    # Enterprise identity (populated from JWT claims, zero extra DB calls)
    use_enterprise_data: bool           # User toggled "Enterprise Data Store" in UI
    org_id: Optional[str]               # Org this user belongs to
    dept_id: Optional[str]              # Department (finer scope)
    roles: List[str]                    # e.g. ['user'] or ['dept_admin', 'user']

    # Analysis results
    query_intent: Optional[QueryIntent]
    selected_strategies: List[RetrievalStrategy]
    decomposed_queries: List[str]  # Legacy field for backward compatibility
    sub_queries: Optional[List[SubQuery]]  # Enhanced sub-query decomposition
    
    # Data routing — vault file metadata is read from MongoDB
    # (`structured_file_metadata` + `unstructured_file_metadata`). The legacy
    # Milvus `saas` collection has been retired; the field name is kept for
    # backward compatibility with downstream consumers.
    requires_data: Optional[bool]  # Whether query needs any data at all
    use_saas_data: Optional[bool]  # Whether to include vault file metadata in retrieval (default: True)

    # Retrieval results
    personal_contexts: List[Dict[str, Any]]
    kg_contexts: List[Dict[str, Any]]  # Knowledge graph contexts for personal folders
    saas_contexts: List[Dict[str, Any]]  # Vault file schema/summary previews from MongoDB metadata
    enterprise_contexts: List[Dict[str, Any]]  # Always empty — kept for downstream-merge compatibility

    # Final results
    merged_context: str
    merged_contexts: List[Dict[str, Any]]  # Raw context chunks for chunk-based caching
    final_response: str
    metadata: Dict[str, Any]
    
    # Processing metadata
    processing_time: float
    strategies_executed: List[str]
    error_messages: List[str]

class QueryOrchestrator:
    """Main orchestrator using LangGraph for agentic RAG"""
    
    def __init__(self):
        self.simplified_planner = SimplifiedStrategyPlanner()  # Intelligent sub-query generator
        self.context_merger = ContextMerger()
        
        # Use unified source provider
        self.source_provider = get_source_provider()
        
        # Initialize retrieval tools (no LLM decisions - just data retrieval)
        # Now includes SaaSDataTool for Milvus saas collection search
        self.tools = RETRIEVAL_TOOLS
        
        # Knowledge Graph Agent disabled (env flag removed — re-add if KG pipeline is restored)
        self.kg_agent = None
        
        # Store reference to planner for legal filter extraction
        self.planner = self.simplified_planner
        
        # Structured data for chat is now handled by SaaSDataTool via source_provider.
        # Other UIs (presentation, printable, composer) call retrieve_for_query directly.
        
        self.graph = self._build_graph()
        logger.info("🚀 QueryOrchestrator initialized with SimplifiedStrategyPlanner, KG Agent, and unified source provider")
    
    def _build_graph(self) -> StateGraph:
        """Build the LangGraph workflow"""
        workflow = StateGraph(QueryState)
        
        # Add nodes
        workflow.add_node("analyze_query", self.analyze_query)
        workflow.add_node("plan_strategies", self.plan_strategies)
        workflow.add_node("execute_retrieval", self.execute_retrieval)
        workflow.add_node("execute_retrieval_with_legal_filter_fallback", self.execute_retrieval_with_legal_filter_fallback)
        workflow.add_node("merge_contexts", self.merge_contexts)
        workflow.add_node("generate_response", self.generate_response)
        
        # Set entry point
        workflow.set_entry_point("analyze_query")
        
        # Define workflow edges
        workflow.add_edge("analyze_query", "plan_strategies")
        
        # Conditional routing based on strategies
        workflow.add_conditional_edges(
            "plan_strategies",
            self.route_execution,
            {
                "retrieval": "execute_retrieval_with_legal_filter_fallback",
                "merge": "merge_contexts"
            }
        )
        
        # Regular retrieval path
        workflow.add_edge("execute_retrieval", "merge_contexts")
        workflow.add_edge("execute_retrieval_with_legal_filter_fallback", "merge_contexts")
        workflow.add_edge("merge_contexts", "generate_response")
        workflow.add_edge("generate_response", END)
        
        return workflow.compile()
    
    async def analyze_query(self, state: QueryState) -> QueryState:
        """Analyze query intent using SimplifiedStrategyPlanner for intelligent sub-query generation"""
        try:
            logger.info(f"🧠 Analyzing query: '{state['query'][:100]}...'")
            
            # Store original query for reference
            original_query = state['query']
            state['original_query'] = original_query
            
            # Prepare user persona data
            persona_data = state.get('persona_data', {})
            
            # Extract profession - handle both nested and flat structures
            if isinstance(persona_data.get('persona'), dict):
                profession = persona_data['persona'].get('profession', 'General User')
            else:
                profession = persona_data.get('profession', 'General User')
            
            logger.info(f"👤 User profession: {profession}")
            
            # Store profession in state for citation control
            state['profession'] = profession
            
            # Available sources - personal only
            available_sources = {
                'personal': state.get('use_personal_data', True),
                'multi_hop': True  # Multi-hop is always available if needed
            }
            
            # ═══════════════════════════════════════════════════════════════════
            # SaaS DATA: Conditionally enabled — conditions:
            #   1. INCLUDE_SUPPLEMENTARY_SOURCES=true in .env
            #   2. use_personal_data is True in state
            #   3. folder_ids is provided (non-empty) — from metadata.selected_folder_ids
            # Structured files surface schema-only previews + sandbox execution
            # (see services/structured_file_listing.py + services/structured_sandbox.py).
            # ═══════════════════════════════════════════════════════════════════
            import os as _os
            _env_saas = _os.getenv("INCLUDE_SUPPLEMENTARY_SOURCES", "false").lower() == "true"
            _use_personal = state.get('use_personal_data', False)
            _folder_ids = state.get('metadata', {}).get('selected_folder_ids', []) or []
            state['use_saas_data'] = bool(
                _env_saas and _use_personal and _folder_ids
            )
            logger.info(
                f"📊 SaaS data search: {'enabled' if state['use_saas_data'] else 'disabled'} "
                f"(env={_env_saas}, personal={_use_personal}, "
                f"folders={bool(_folder_ids)})"
            )
            
            # ── Agentic mode: NO sub-query planner LLM ───────────────────────
            # The chat LLM is itself agentic — at answer time it decides what to
            # retrieve via personal_data_tool / dept_* MCP tools. A separate
            # planner LLM here only added a serial LLM round-trip to first-token
            # latency without changing what the agent ultimately fetches. Pass the
            # query through unchanged as a single sub-query — the exact shape the
            # downstream retrieval/merge path already handles (identical to the
            # former analysis-failure fallback, which is known-good).
            state['query_intent'] = QueryIntent(
                needs_decomposition=False,
                sub_queries=[SubQuery(query_text=original_query, priority=1)],
                original_complexity='simple',
                original_query=original_query,
                enhanced_query=original_query,
            )
            state['sub_queries'] = state['query_intent'].sub_queries
            state['decomposed_queries'] = [original_query]
            state['requires_data'] = True
            logger.info(
                "🧠 [ANALYZE] sub-query planner skipped (agentic) — query passed "
                "through as a single sub-query; chat LLM drives retrieval"
            )
            
        except Exception as e:
            logger.error(f"❌ Query analysis failed: {e}", exc_info=True)
            # Fallback: create simple single sub-query
            state['query_intent'] = QueryIntent(
                needs_decomposition=False,
                sub_queries=[SubQuery(
                    query_text=state['query'],
                    priority=1,
                    reasoning='Fallback due to analysis error'
                )],
                original_complexity='simple',
                original_query=state['query'],
                enhanced_query=state['query']
            )
            state['sub_queries'] = state['query_intent'].sub_queries
            state['decomposed_queries'] = [state['query']]
            state['error_messages'] = state.get('error_messages', []) + [f"Query analysis failed: {str(e)}"]
        
        return state
    
    async def plan_strategies(self, state: QueryState) -> QueryState:
        """
        Plan retrieval strategies based on enabled sources and LLM analysis
        
        NEW ARCHITECTURE:
        - SimplifiedStrategyPlanner generates optimized query text
        - Orchestrator decides which tools to use based on:
          1. use_personal_data flag
        """
        try:
            logger.info("🎯 Planning retrieval strategies...")
            
            intent = state['query_intent']
            if not intent:
                logger.error("❌ No query intent available for strategy planning")
                state['selected_strategies'] = [RetrievalStrategy.PERSONAL_ONLY]
                return state
            
            strategies = []
            
            logger.info(f"📊 Source availability:")
            logger.info(f"   - Personal: {state.get('use_personal_data', True)}")
            logger.info(f"   - Enterprise: {state.get('use_enterprise_data', False)}")
            
            # PERSONAL STRATEGY
            if state.get('use_personal_data', True):
                strategies.append(RetrievalStrategy.PERSONAL_ONLY)
                logger.info("✅ Added PERSONAL_ONLY strategy")
            else:
                logger.info("⏭️ Skipping PERSONAL_ONLY strategy (use_personal_data=False)")
            
            # ENTERPRISE STRATEGY — added independently; combined with personal if both on
            if state.get('use_enterprise_data', False):
                strategies.append(RetrievalStrategy.ENTERPRISE)
                logger.info("✅ Added ENTERPRISE strategy")
            
            # Fallback if no strategies — only add personal if use_personal_data was not explicitly disabled
            if not strategies:
                if state.get('use_personal_data', True):
                    strategies.append(RetrievalStrategy.PERSONAL_ONLY)
                    logger.info("ℹ️ No strategies determined, using PERSONAL_ONLY fallback")
                else:
                    logger.info("ℹ️ No strategies and vault disabled — model-only mode, skipping retrieval")
            
            state['selected_strategies'] = strategies
            logger.info(f"🎯 Final strategy plan: {[s.value for s in strategies]}")
            
        except Exception as e:
            logger.error(f"❌ Strategy planning failed: {e}")
            state['error_messages'] = state.get('error_messages', []) + [f"Strategy planning failed: {str(e)}"]
            # Fallback to personal only
            state['selected_strategies'] = [RetrievalStrategy.PERSONAL_ONLY]
        
        return state
    
    def route_execution(self, state: QueryState) -> str:
        """Route to appropriate execution path"""
        strategies = state.get('selected_strategies', [])
        
        # If any retrieval strategies are needed
        if strategies:
            return "retrieval"
        
        # Fallback to merge (with empty contexts)
        return "merge"
    
    async def execute_retrieval(self, state: QueryState) -> QueryState:
        """Execute retrieval strategies using unified source provider."""
        try:
            logger.info("🔍 Executing retrieval strategies...")
            
            strategies = state.get('selected_strategies', [])
            query_intent = state.get('query_intent')

            # Build SourceConfig — after the agentic-tool refactor, the only
            # pre-fetched source is SaaSDataTool (Mongo file-listing metadata).
            # Personal vault chunks and enterprise data are fetched on-demand
            # by the chat LLM via `personal_data_tool` and `dept_*` MCP tools.
            source_config = self.source_provider.build_source_config_from_strategies(strategies, state)

            async def fetch_all_contexts():
                """Pre-fetch file-listing metadata via SaaSDataTool (Mongo).

                Sub-queries from the planner are intentionally NOT used here:
                file listings are scoped by user_id + folder_ids, not by query
                semantics, so one call suffices. The planner's sub_queries
                surface again inside `personal_data_tool` when the chat LLM
                actually fetches vault chunks on demand.
                """
                query_to_use = state['query']
                if query_intent and query_intent.sub_queries and len(query_intent.sub_queries) == 1:
                    # Single sub-query is a refined version of state['query'] —
                    # use it for slightly better file-relevance scoring.
                    query_to_use = query_intent.sub_queries[0].query_text
                contexts_by_source = await self.source_provider.retrieve_from_sources(
                    query=query_to_use,
                    user_id=state['user_id'],
                    source_config=source_config,
                    context_label="file_metadata_prefetch",
                    user_email=state.get('user_email'),
                )
                total_contexts = sum(len(c) for c in contexts_by_source.values())
                logger.info(f"✅ File-metadata pre-fetch: {total_contexts} chunk(s)")
                return contexts_by_source

            logger.info("🚀 Starting file-metadata pre-fetch (personal vault chunks fetched agentically by chat LLM)...")
            contexts_by_source = await fetch_all_contexts()
            logger.info("✅ Pre-fetch complete")
            
            # Process results
            total_contexts = sum(len(contexts) for contexts in contexts_by_source.values())
            
            # Store retrieved contexts in state (maintaining backward compatibility).
            # personal_contexts is always empty after the agentic-tool refactor —
            # the chat LLM fetches Milvus chunks via personal_data_tool on demand.
            state['personal_contexts'] = []
            state['saas_contexts'] = contexts_by_source.get('saas', [])  # File-listing metadata from Mongo
            state['contexts_by_source'] = contexts_by_source

            # ═══════════════════════════════════════════════════════════════════
            # ENTERPRISE: orchestrator pre-fetch is DEPRECATED. All enterprise
            # retrieval now happens via the LLM-callable `dept_*` MCP tools
            # surfaced in streaming_response.py. Keep the state field empty for
            # backward compatibility with downstream merging logic.
            # ═══════════════════════════════════════════════════════════════════
            state['enterprise_contexts'] = []
            
            # Log SaaS retrieval results
            saas_count = len(state['saas_contexts'])
            if saas_count > 0:
                logger.info(f"✅ [SAAS] Retrieved {saas_count} contexts from Milvus saas collection")
                state['strategies_executed'] = state.get('strategies_executed', []) + ['saas_search']
            else:
                logger.info("⏭️ [SAAS] No SaaS data found (user may not have connected sources)")
            
            # ═══════════════════════════════════════════════════════════════════
            # SEQUENTIAL: Knowledge Graph (less common)
            # ═══════════════════════════════════════════════════════════════════
            
            # 🧠 KNOWLEDGE GRAPH RETRIEVAL: Disabled (env flag removed)
            state['kg_contexts'] = []
            
            # ═══════════════════════════════════════════════════════════════════
            # NOTE: SaaS DATA is now retrieved automatically via SaaSDataTool
            # - Data is pre-embedded into Milvus `saas` collection by file upload
            # - SaaSDataTool performs semantic search in parallel with personal data
            # - No need for separate live_data fetching or AI routing
            # ═══════════════════════════════════════════════════════════════════
            
            # Track executed strategies (excluding removed MULTI_HOP)
            executed_strategies = [s.value for s in strategies]
            state['strategies_executed'] = state.get('strategies_executed', []) + executed_strategies
            
            logger.info(f"✅ Retrieval execution complete - {total_contexts} total contexts from {len(contexts_by_source)} sources")
            
        except Exception as e:
            logger.error(f"❌ Retrieval execution failed: {e}")
            state['error_messages'] = state.get('error_messages', []) + [f"Retrieval execution failed: {str(e)}"]
        
        return state

    async def execute_retrieval_with_legal_filter_fallback(
        self, 
        state: QueryState,
        min_score_threshold: Optional[float] = None
    ) -> QueryState:
        """
        🔬 PHASE 3: Orchestrator Fallback Logic (DEPRECATED)
        This method is deprecated and now just calls standard retrieval.
        Legal metadata filtering has been removed from the system.
        
        This method is kept for backward compatibility but no longer performs
        any special filtering or fallback logic
        
        Args:
            state: Current query state with user context
            min_score_threshold: Optional minimum relevance score override
                                 If None, uses adaptive threshold based on search type:
                                 - Hybrid search: 5.0 (scores range 0-50+ due to BM25 + cosine)
                                 - Dense-only: 0.5 (cosine similarity: 0-1 range)
            
        Returns:
            Updated state with retrieved contexts and filter metadata
            
        State Updates:
            - personal_contexts/enterprise_contexts/entity_contexts: Retrieved results
            - legal_filter_metadata: Dict with filter application details
                {
                    "filter_extracted": bool,
                    "filter_applied": bool,
                    "fallback_triggered": bool,
                    "initial_result_count": int,
                    "final_result_count": int,
                    "max_score": float,
                    "filter_confidence": str,
                    "filter_used": Dict,
                    "strategy": str  # "filtered_success" | "fallback_no_filter" | "no_filter_needed"
                }
                
        """
        logger.info("🔬 PHASE 3: Executing standard retrieval (legal filtering removed)")
        return await self.execute_retrieval(state)
    
    def _convert_filtered_results_to_contexts(
        self, 
        results: List[Dict[str, Any]], 
        strategies: List[RetrievalStrategy]
    ) -> Dict[str, List[Dict[str, Any]]]:
        """
        Convert filtered query results to context format expected by downstream components.
        
        Args:
            results: List of results from query_with_legal_metadata_filter
            strategies: List of retrieval strategies to determine context categorization
            
        Returns:
            Dict with keys: personal
        """
        contexts = {
            'personal': []
        }
        
        for result in results:
            context = {
                'text': result.get('metadata', {}).get('text', ''),
                'metadata': result.get('metadata', {}),
                'score': result.get('score', 0.0),
                'node_id': result.get('id')
            }
            
            # All results go to personal context
            contexts['personal'].append(context)
        
        return contexts
    
    async def _execute_personal_retrieval(self, state: QueryState, contexts_by_source: Dict):
        """Execute personal data retrieval using tool"""
        contexts = await self.tools['personal'].retrieve(
            query=state['query'],
            user_id=state['user_id'],
            max_results=20,  # Increased to ensure outcome chunks are included
            selected_folder_ids=state.get('selected_folder_ids', []),
            folder_search_enabled=state.get('folder_search_enabled', False)
        )
        contexts_by_source['personal'] = contexts
    
    async def merge_contexts(self, state: QueryState) -> QueryState:
        """Merge and rank contexts from all sources"""
        try:
            logger.info("🔄 Merging and ranking contexts...")
            
            # 🔧 PARALLEL EXECUTION FIX: Check for contexts_by_source first (from parallel/retrieval execution)
            contexts_by_source = state.get('contexts_by_source', {})
            
            # Fallback to legacy individual context keys if contexts_by_source is empty
            if not contexts_by_source:
                logger.info("📋 Using legacy context keys (personal_contexts)")
                contexts_by_source = {}
                
                if state.get('personal_contexts'):
                    contexts_by_source['personal'] = state['personal_contexts']
            else:
                logger.info(f"📋 Using contexts_by_source from parallel/retrieval execution: {len(contexts_by_source)} sources")

            # Merge enterprise contexts into contexts_by_source so ContextMerger ranks them together
            enterprise_ctxs = state.get('enterprise_contexts', [])
            if enterprise_ctxs:
                contexts_by_source['enterprise'] = enterprise_ctxs
                logger.info(f"✅ [ENTERPRISE] Injecting {len(enterprise_ctxs)} enterprise contexts into merge")
            
            if not contexts_by_source:
                logger.warning("⚠️ No contexts available for merging")
                state['merged_context'] = ""
                return state
            
            # 🎯 DYNAMIC CONTEXT LIMIT: Based on total contexts retrieved
            # After parallel sub-query execution, we may have many duplicate chunks
            # Context Merger will deduplicate and rank by relevance
            query_intent = state.get('query_intent')
            complexity = query_intent.original_complexity if query_intent else 'simple'
            num_sub_queries = len(query_intent.sub_queries) if query_intent and query_intent.sub_queries else 1
            needs_decomposition = query_intent.needs_decomposition if query_intent else False
            
            # Calculate total contexts retrieved
            total_retrieved = sum(len(contexts) for contexts in contexts_by_source.values())
            logger.info(f"📊 Total contexts retrieved: {total_retrieved}")
            
            # 🎯 DYNAMIC CONTEXT LIMIT: Based on query complexity only
            # For complex queries with parallel sub-query execution, use ALL retrieved chunks
            # Deduplication will naturally reduce redundancy (~70% for typical cases)
            # Context Merger will rank and select the most relevant chunks
            if complexity == 'complex':
                # Complex queries: up to 35 final contexts for rich multi-faceted grounding.
                max_contexts = min(total_retrieved, 35)
                min_contexts = 15
                logger.info(f"📊 Complex query detected: using up to {max_contexts} contexts from {total_retrieved} retrieved")
            elif complexity == 'moderate' or needs_decomposition:
                # Moderate queries: up to 25 final contexts.
                max_contexts = min(total_retrieved, 25)
                min_contexts = 15
                logger.info(f"📊 Moderate query detected: using up to {max_contexts} contexts from {total_retrieved} retrieved")
            else:
                # Simple queries: up to 15 final contexts, guaranteed minimum 10.
                max_contexts = min(total_retrieved, 15)
                min_contexts = 10
                logger.info(f"📊 Simple query detected: using up to {max_contexts} contexts from {total_retrieved} retrieved")

            # 🔒 FLOOR GUARANTEE: Ensure LLM always receives at least min_contexts chunks.
            # Protects against heavy deduplication reducing the pool below the useful minimum.
            # Uses all available if fewer exist than the floor (can't manufacture chunks).
            effective_contexts = max(max_contexts, min(total_retrieved, min_contexts))
            if effective_contexts != max_contexts:
                logger.info(f"📊 Floor applied: bumping context count from {max_contexts} → {effective_contexts} (floor={min_contexts}, available={total_retrieved})")
            max_contexts = effective_contexts
            
            # Merge and rank contexts with dynamic limit
            logger.debug(f"🔍 DEBUG: About to merge contexts - contexts_by_source keys: {list(contexts_by_source.keys())}")
            for source_key, source_contexts in contexts_by_source.items():
                logger.debug(f"🔍 DEBUG: {source_key}: {len(source_contexts)} contexts")
                if source_contexts and len(source_contexts) > 0:
                    first_context = source_contexts[0]
                    logger.debug(f"🔍 DEBUG: Sample {source_key} context keys: {list(first_context.keys())}")
                    logger.debug(f"🔍 DEBUG: Sample {source_key} text preview: {first_context.get('text', first_context.get('content', ''))[:200]}...")
            
            merge_result = await self.context_merger.merge_and_rank_contexts(
                query=state['query'],
                contexts_by_source=contexts_by_source,
                max_contexts=max_contexts,
                user_id=state.get('user_id'),
                user_email=state.get('user_email')
            )
            
            # Create formatted context for LLM
            formatted_context = await self.context_merger.create_response_context(
                query=state['query'],
                merged_contexts=merge_result['merged_contexts'],
                query_decomposition=state.get('decomposed_queries'),
                profession=state.get('profession')  # Pass profession for citation control
            )
            
            state['merged_context'] = formatted_context
            state['merged_contexts'] = merge_result['merged_contexts']  # Store for score checking
            
            # ═══════════════════════════════════════════════════════════════════
            # SAAS DATA INTEGRATION
            # SaaS contexts already flow through contexts_by_source['saas'] via
            # SourceProvider → SaaSDataTool → merge_and_rank_contexts above.
            # No separate prepend needed — that caused double-counting.
            # Just log how many made it through the merge.
            # ═══════════════════════════════════════════════════════════════════
            saas_contexts = state.get('saas_contexts', [])
            if saas_contexts:
                logger.info(f"📊 [SAAS] {len(saas_contexts)} SaaS contexts available (merged via contexts_by_source)")
            
            # ═══════════════════════════════════════════════════════════════════
            # STRUCTURED DATA: Handled by SaaSDataTool via source_provider
            # (Phase 4 execute_retrieval). No duplicate fetch needed here.
            # The SaaSDataTool result arrives in contexts_by_source['saas']
            # and is already merged above via merge_and_rank_contexts.
            # ═══════════════════════════════════════════════════════════════════
            
            # Add metadata
            state['metadata'] = state.get('metadata', {})
            state['metadata'].update({
                'contexts_merged': merge_result['total_contexts'],
                'source_distribution': merge_result['source_distribution']
            })
            
            # Add SaaS metadata if present
            if saas_contexts:
                state['metadata']['saas_contexts_count'] = len(saas_contexts)
            
            logger.info(f"✅ Context merging complete - {merge_result['total_contexts']} contexts")
            
        except Exception as e:
            logger.error(f"❌ Context merging failed: {e}")
            state['error_messages'] = state.get('error_messages', []) + [f"Context merging failed: {str(e)}"]
            state['merged_context'] = ""
        
        return state
    
    async def generate_response(self, state: QueryState) -> QueryState:
        """Generate final response using LLM with persona awareness - integrates multi-hop as context source"""
        try:
            logger.info("🤖 Generating comprehensive response with multi-hop integration...")

            # 🔄 MULTI-HOP INTEGRATION: Convert multi-hop results to contexts for merging
            # Multi-hop should contribute insights, not replace the entire response generation
            if state.get('multi_hop_result'):
                logger.info("🔬 Integrating multi-hop insights as additional context source")
                
                multi_hop_result = state.get('multi_hop_result', {})
                multi_hop_insights = multi_hop_result.get('final_answer', '')
                
                # Convert multi-hop insights into context format for integration
                if multi_hop_insights and multi_hop_insights.strip():
                    # Clean multi-hop response of SOURCES section for integration
                    cleaned_insights = multi_hop_insights.split('SOURCES:')[0].strip() if 'SOURCES:' in multi_hop_insights else multi_hop_insights
                    
                    multi_hop_context = {
                        'content': f"**Multi-Hop Analysis Results:**\n\n{cleaned_insights}",
                        'source': 'multi_hop_reasoning',
                        'relevance_score': 0.95,  # High relevance as it's targeted analysis
                        'metadata': {
                            'source_type': 'multi_hop_analysis',
                            'hops_completed': multi_hop_result.get('hops_completed', 0),
                            'confidence_score': multi_hop_result.get('confidence_score', 0.8),
                            'reasoning_path': multi_hop_result.get('reasoning_path', [])
                        }
                    }
                    
                    # Add multi-hop context to existing merged context
                    existing_context = state.get('merged_context', '')
                    if existing_context:
                        # Prepend multi-hop insights to existing context (high priority)
                        enhanced_context = f"{multi_hop_context['content']}\n\n---\n\n**Additional Retrieved Information:**\n{existing_context}"
                        state['merged_context'] = enhanced_context
                        logger.info("🔗 Enhanced existing context with multi-hop insights")
                    else:
                        # Use multi-hop as primary context if no other context available
                        state['merged_context'] = multi_hop_context['content']
                        logger.info("🔗 Using multi-hop insights as primary context")
                    
                    # Store multi-hop citations for later integration
                    state['multi_hop_citations'] = multi_hop_result.get('multi_hop_citations', [])
                else:
                    logger.warning("⚠️ Multi-hop result exists but no insights found")

            logger.info("🤖 Generating unified response with all context sources...")

            attachments = state.get('multimodal_attachments') or []
            attachments_summary = ""
            if attachments:
                summary_lines = []
                for idx, attachment in enumerate(attachments, start=1):
                    name = attachment.get('name') or attachment.get('id') or f"attachment-{idx}"
                    mime_type = attachment.get('mimeType') or attachment.get('type') or 'application/octet-stream'
                    size_bytes = attachment.get('size') or 0
                    size_kb = int(size_bytes / 1024) if size_bytes else 0
                    summary_lines.append(f"{idx}. {name} ({mime_type}, ~{size_kb} KB)")
                attachments_summary = "\n\nUser provided the following attachments (use them when relevant):\n" + "\n".join(summary_lines)

            # Import here to avoid circular imports
            import sys
            import os
            # Add parent directory to path so we can import query module
            parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            if parent_dir not in sys.path:
                sys.path.insert(0, parent_dir)
            from query import reply

            # 🎯 PERSONA INTEGRATION: Generate persona-aware system prompt with citations
            persona_system_prompt = None
            profession = None  # Extract profession for collections access control
            try:
                persona_data = state.get('persona_data')
                if persona_data:
                    # Add parent directory to path for persona import
                    import sys
                    import os
                    parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
                    if parent_dir not in sys.path:
                        sys.path.insert(0, parent_dir)
                    from persona import generate_persona_system_prompt
                    # Use persona prompt for final response generation
                    persona_system_prompt = generate_persona_system_prompt(persona_data)
                    
                    # Log the actual profession from persona data and extract for collections check
                    persona_info = persona_data.get('persona', {})
                    profession = persona_info.get('profession', persona_data.get('profession'))  # Handle nested and flat structures
                    logger.info(f"🎯 [ORCHESTRATOR] Generated persona-aware system prompt for profession: {profession}")
                else:
                    logger.info("🎯 [ORCHESTRATOR] No persona data provided - using default prompt")
            except ImportError:
                logger.warning("🎯 [ORCHESTRATOR] Persona module not available")
            except Exception as e:
                logger.warning(f"🎯 [ORCHESTRATOR] Error generating persona prompt: {e}")

            # Get conversation history (last-5 + truncation handled downstream in conversation_messages loop)
            conversation_history = state.get('conversation_history', [])

            # Display original query to user (if query was enriched, show original to user)
            display_query = state.get('original_query', state['query'])
            
            # 🔍 DEBUG: Log merged_context to see if chunks are included
            merged_context = state.get('merged_context', '')
            logger.info(f"🔍 DEBUG: merged_context length: {len(merged_context)} characters")
            if merged_context:
                logger.info(f"🔍 DEBUG: merged_context preview: {merged_context[:500]}...")
            else:
                logger.warning("⚠️ DEBUG: merged_context is EMPTY - no chunks will be sent to LLM!")
            
            # ═══════════════════════════════════════════════════════════════════════════════════════
            # 🚀 XAI PROMPT CACHING OPTIMIZATION v2.0 - CHUNK-BASED CACHING
            # ═══════════════════════════════════════════════════════════════════════════════════════
            # NEW APPROACH: Each chunk as separate message AFTER conversation history
            # 
            # Message order for optimal cache stability:
            # 1. System message (persona - static per user) - CACHED
            # 2. Conversation history (previous turns) - CACHED
            # 3. Context chunk #1 (sorted by chunk_id) - CACHED if seen before
            # 4. Context chunk #2 (sorted by chunk_id) - CACHED if seen before
            # ... 
            # N. Context chunk #N (sorted by chunk_id) - CACHED if seen before
            # N+1. Current query (varies each time) - NOT CACHED
            #
            # WHY THIS WORKS BETTER:
            # - Old approach: All chunks in one message → any new chunk breaks ENTIRE context cache
            # - New approach: Each chunk = separate message → only NEW chunks break cache
            # - Example: 10 cached chunks + 2 new = 10 stay cached, only 2 new messages added
            # - Cache stability: ~70-90% even when new documents added to folder
            #
            # Cached input tokens are billed at a large discount vs. fresh input tokens (~83% fewer tokens per cached chunk)
            # ═══════════════════════════════════════════════════════════════════════════════════════
            
            # Get raw merged contexts (list of chunk dicts) instead of formatted string
            context_chunks = state.get('merged_contexts', [])
            
            # Convert conversation history to structured messages for caching
            # Keep last 5 messages: user queries full, bot replies truncated to 400 words
            conversation_messages = []
            if conversation_history:
                for msg in conversation_history[-5:]:  # Keep last 5 messages
                    if isinstance(msg, dict):
                        role = msg.get('role', 'user')
                        content = msg.get('content', msg.get('message', msg.get('user_query', ''))).strip()
                        if content:
                            # Truncate bot replies to 400 words, keep user queries full
                            if role != 'user':
                                words = content.split()
                                if len(words) > 400:
                                    content = ' '.join(words[:400]) + "..."
                            conversation_messages.append({
                                'role': role,
                                'content': content
                            })
            
            logger.info(f"🔥 [XAI_CACHE] Prepared for CHUNK-BASED caching optimization:")
            logger.info(f"   - context_chunks: {len(context_chunks)} individual chunks (each as separate message)")
            logger.info(f"   - conversation_history: {len(conversation_messages)} messages")
            logger.info(f"💡 [XAI_CACHE] New chunks won't break cache for existing chunks!")
            
            # Create minimal response prompt (current query only - NOT cached)
            response_prompt = f"""Based on the document context provided, answer the user's question comprehensively.{attachments_summary}

User Query: {display_query}

After your answer, always end with 2–3 follow-up suggestions under a "**You might also ask:**" label to help continue the conversation."""


            # 🎯 MODEL SELECTION: Choose model based on attachment types
            # - LLM (default model): All queries including image attachments
            # Note: Audio attachments are already transcribed to text in query.py before reaching here
            
            has_image_attachments = any(
                (att.get('mimeType') or att.get('type') or '').lower().startswith('image/')
                for att in attachments
            )
            
            if has_image_attachments:
                model_to_use = get_default_model()
                logger.info(f"🖼️ [MODEL_SELECTION] Image attachment detected - using {model_to_use}")
            else:
                model_to_use = get_default_model()
                logger.info(f"📝 [MODEL_SELECTION] Text-only query - using {model_to_use}")
            
            # 🌐 INTERNET SEARCH CONTROL - adaptive gating via rag.retrieval_guard
            # If vault is authoritative (max_score >= MIN_VAULT_TRUST) we suppress
            # internet_search for this turn; if vault is empty/low-signal we keep it.
            # Users can override with `force_internet=True` in the request payload.

            try:
                from rag.retrieval_guard import (
                    assess_context, decide_internet_search,
                    tag_chunks_with_origin, grounding_log_event,
                )
            except Exception as _guard_err:
                logger.warning(f"⚠️ retrieval_guard import failed: {_guard_err}; falling back to user-toggle only")
                assess_context = None
                decide_internet_search = None
                tag_chunks_with_origin = None
                grounding_log_event = None

            user_enabled_internet = bool(state.get('enable_internet_search', False))
            force_internet = bool(state.get('force_internet', False))

            # Tag chunks with source_origin so reply_llm can render typed headers
            # ([VAULT CHUNK ...] / [INTERNET CHUNK ...] / [STRUCTURED CHUNK ...]).
            if tag_chunks_with_origin and context_chunks:
                # Heuristic default: enterprise contexts come from `enterprise_contexts`,
                # SaaS chunks already carry source_type=structured_sql in metadata.
                tagged_chunks: List[Dict[str, Any]] = []
                for _ch in context_chunks:
                    if not isinstance(_ch, dict):
                        continue
                    if 'source_origin' in _ch:
                        tagged_chunks.append(_ch)
                        continue
                    meta = _ch.get('metadata') or {}
                    src_type = (meta.get('source_type') or '').lower()
                    if 'structured' in src_type or 'saas' in src_type or 'sql' in src_type:
                        origin = 'structured'
                    elif 'internet' in src_type or 'web' in src_type:
                        origin = 'internet'
                    elif 'enterprise' in src_type:
                        origin = 'enterprise'
                    else:
                        origin = 'vault'
                    _new = dict(_ch)
                    _new['source_origin'] = origin
                    tagged_chunks.append(_new)
                context_chunks = tagged_chunks
                state['merged_contexts'] = tagged_chunks  # keep state consistent

            # Assess retrieval quality
            quality = None
            if assess_context:
                quality = assess_context(
                    chunks=context_chunks,
                    formatted_text=state.get('merged_context'),
                )

            # Decide whether internet_search should be enabled this turn
            if decide_internet_search and quality is not None:
                decision = decide_internet_search(
                    quality=quality,
                    user_enabled=user_enabled_internet,
                    force_internet=force_internet,
                )
                enable_internet = decision['enabled']
                if grounding_log_event:
                    grounding_payload = grounding_log_event(
                        feature='main_chat',
                        quality=quality,
                        decision=decision,
                        request_id=state.get('request_id'),
                    )
                    state['metadata'] = state.get('metadata', {})
                    state['metadata']['grounding'] = grounding_payload
                    state['metadata']['grounding']['internet_used'] = enable_internet
            else:
                enable_internet = user_enabled_internet
                logger.info(f"🌐 Internet search (no guard): user={user_enabled_internet}")

            logger.info(f"🔧 [TOOL_SELECTION] Internet search: {enable_internet}")

            # 📊 Emit Prometheus grounding metrics (best-effort, never raises)
            try:
                from metrics import record_grounding
                record_grounding(
                    feature='main_chat',
                    chunks_used=len(context_chunks) if context_chunks else 0,
                    context_empty=(quality is not None and not quality.has_context),
                    temperature=None,  # set below after temperature_for() resolved
                    internet_used=bool(enable_internet),
                    internet_reason=(
                        decision.get('reason', '') if 'decision' in locals() and isinstance(decision, dict) else ''
                    ),
                )
            except Exception as _m_err:
                logger.debug(f"record_grounding skipped: {_m_err}")

            # 🛡️ RETRIEVAL-EMPTY GUARD — when no chunks at all, append explicit
            # "no sources" wrapper to the system prompt so the LLM falls back to
            # IDK / general-knowledge tagging instead of silent training-knowledge
            # hallucination. We append AFTER persona so persona caching still works.
            try:
                if quality is not None and not quality.has_context:
                    from prompts.grounding import no_context_wrapper
                    no_ctx_block = no_context_wrapper(internet_available=enable_internet)
                    persona_system_prompt = (
                        (persona_system_prompt or "")
                        + "\n\n---\n\n"
                        + no_ctx_block
                    )
                    logger.info(f"🛡️ [GROUNDING] No vault context — injected no-context wrapper (internet={enable_internet})")
            except Exception as _wrap_err:
                logger.warning(f"⚠️ no-context wrapper injection failed: {_wrap_err}")

            # 🎚️ TEMPERATURE PROFILE — pick from llm.llm_defaults based on profession
            try:
                from llm.llm_defaults import temperature_for
                _resolved_temperature = temperature_for()
            except Exception:
                _resolved_temperature = None
            if _resolved_temperature is not None:
                logger.info(f"🌡️ [TEMP_PROFILE] profession={profession} → T={_resolved_temperature}")
            
            # 🚀 XAI CACHING: Pass context_chunks as list instead of static_context string
            # Sorting is done in query.py before sending to xAI
            response = reply(
                response_prompt,  # Current query only (not cached)
                model_to_use,
                system=persona_system_prompt,  # CACHED - static per user
                attachments=attachments,
                enable_internet_search=enable_internet,
                user_id=state.get('user_id'),
                user_email=state.get('user_email'),
                profession=profession,
                context_chunks=context_chunks,  # NEW: Each chunk as separate message for optimal caching
                conversation_history=conversation_messages,  # CACHED - previous turns as messages
                temperature=_resolved_temperature,  # 🌡️ profession-aware temperature
                tier="large",
            )
            state['final_response'] = response

            logger.info("✅ Persona-aware response generation complete")
        except Exception as e:
            logger.error(f"❌ Response generation failed: {e}")
            state['error_messages'] = state.get('error_messages', []) + [f"Response generation failed: {str(e)}"]
            state['final_response'] = "An error occurred while generating the response. Please try again."

        return state

    # Note: Old _generate_unified_citations method removed - it incorrectly extracted from contexts
    # Citations are now properly extracted from LLM responses only in _extract_unified_citations_for_api()

    # def _extract_unified_citations_for_api(self, result: QueryState) -> List[Dict[str, str]]:
    #     """
    #     Extract unified citations for API response from LLM response SOURCES section only.
    #     This ensures we only return citations that the LLM actually referenced in its response.
    #     """
    #     citations = []
    #     seen_document_ids = set()
        
    #     # Get the final LLM response
    #     final_response = result.get('final_response', '')
        
    #     # Check if LLM response contains SOURCES section
    #     if 'SOURCES:' not in final_response:
    #         logger.info("🔍 No SOURCES section found in LLM response - returning empty citations")
    #         return []
        
    #     # Extract SOURCES section from LLM response
    #     sources_section = final_response.split('SOURCES:')[1].strip()
        
    #     if not sources_section:
    #         logger.info("🔍 SOURCES section is empty - returning empty citations")
    #         return []
        
    #     logger.info(f"🔍 Extracting citations from LLM SOURCES section: {sources_section[:200]}...")
        
    #     # Parse each line in the SOURCES section
    #     import re
    #     for line in sources_section.split('\n'):
    #         line = line.strip()
    #         if not line or line.startswith('#'):
    #             continue
            
    #         # Look for citation patterns in the sources section
    #         # Pattern 1: "topic--document_id" or "topic--URL" format (including with leading dash/bullet)
    #         citation_match = re.search(r'^-?\s*(.+?)--(.+)$', line)
    #         if citation_match:
    #             topic = citation_match.group(1).strip()
    #             identifier = citation_match.group(2).strip()
                
    #             # Create document_id from identifier (URL or document ID)
    #             if identifier.startswith('http://') or identifier.startswith('https://'):
    #                 # Web source - create hash-based ID
    #                 import hashlib
    #                 url_hash = hashlib.md5(identifier.encode()).hexdigest()[:12]
    #                 document_id = f"web_{url_hash}"
    #                 topic_with_url = f"{topic}--{identifier}"
    #             else:
    #                 # RAG document source
    #                 document_id = identifier
    #                 topic_with_url = topic
                
    #             if document_id not in seen_document_ids:
    #                 citation_obj = {
    #                     "document_id": document_id,
    #                     "topic": topic_with_url if identifier.startswith('http') else topic,
    #                     "source": "llm_response"
    #                 }
    #                 citations.append(citation_obj)
    #                 seen_document_ids.add(document_id)
    #                 logger.debug(f"✅ Extracted citation: {topic} -> {document_id}")
    #             continue
        
    #     # Include multi-hop citations if available
    #     if result.get('multi_hop_result'):
    #         multi_hop_citations = result['multi_hop_result'].get('multi_hop_citations', [])
    #         for citation in multi_hop_citations:
    #             if citation.get('document_id') not in seen_document_ids:
    #                 citations.append(citation)
    #                 seen_document_ids.add(citation.get('document_id'))
    #                 logger.debug(f"✅ Added multi-hop citation: {citation.get('topic')} -> {citation.get('document_id')}")
        
    #     # Include multi-hop citations stored during response generation
    #     if result.get('multi_hop_citations'):
    #         for citation in result['multi_hop_citations']:
    #             if citation.get('document_id') not in seen_document_ids:
    #                 citations.append(citation)
    #                 seen_document_ids.add(citation.get('document_id'))
    #                 logger.debug(f"✅ Added stored multi-hop citation: {citation.get('topic')} -> {citation.get('document_id')}")
        
    #     logger.info(f"🔍 Extracted {len(citations)} citations from LLM response SOURCES section")
    #     return citations

    # ═══════════════════════════════════════════════════════════════════════════════════════
    # �🚀 STREAMING SUPPORT: Process query up to context retrieval, skip response generation
    # ═══════════════════════════════════════════════════════════════════════════════════════
    
    async def process_query_for_streaming(
        self,
        query: str,
        user_id: str,
        user_email: Optional[str] = None,
        use_personal_data: bool = True,
        use_enterprise_data: bool = False,
        org_id: Optional[str] = None,
        dept_id: Optional[str] = None,
        roles: Optional[List[str]] = None,
        conversation_history: Optional[List[Dict]] = None,
        multimodal_attachments: Optional[List[Dict[str, Any]]] = None,
        additional_sources: Optional[Dict[str, Any]] = None,
        persona_data: Optional[Dict] = None,
        enable_internet_search: bool = False,
        stage_emit: Optional[Any] = None,
    ) -> Dict[str, Any]:
        """
        Process query through retrieval pipeline WITHOUT generating the final response.
        
        This method is designed for streaming: it retrieves and merges contexts,
        then returns them so the caller can stream the LLM response separately.
        
        Returns:
            Dict with context_chunks, persona_system_prompt, conversation_messages, etc.
        """
        start_time = time.time()
        
        try:
            logger.info(f"🚀 [STREAMING_PREP] Preparing context for streaming query: '{query[:100]}...'")
            
            # Use conversation history directly — last-5 selection happens downstream
            processed_conversation_history = conversation_history or []
            
            # Extract additional source flags
            additional_sources = additional_sources or {}
            selected_folder_ids = additional_sources.get('selected_folder_ids', [])
            folder_search_enabled = additional_sources.get('folder_search_enabled', False)
            
            attachments = multimodal_attachments or []

            # Best-effort STAGE emitter — wraps the optional callback so failures
            # in the timeline never break the retrieval pipeline.
            def _emit(stage: str, label: str, detail: Optional[str] = None) -> None:
                if stage_emit is None:
                    return
                try:
                    stage_emit(stage, label, detail)
                except Exception as _e:  # noqa: BLE001
                    logger.debug(f"[STREAMING_PREP] stage_emit failed for {stage}: {_e}")

            # Build a modified graph that stops BEFORE generate_response
            # OR manually run the retrieval steps
            
            # Initialize state for retrieval-only processing
            initial_state = QueryState(
                query=query,
                user_id=user_id,
                user_email=user_email,
                use_personal_data=use_personal_data,
                use_enterprise_data=use_enterprise_data,
                org_id=org_id,
                dept_id=dept_id,
                roles=roles or ["user"],
                conversation_history=processed_conversation_history,
                multimodal_attachments=attachments,
                persona_data=persona_data,
                enable_internet_search=enable_internet_search,
                personal_contexts=[],
                enterprise_contexts=[],
                kg_contexts=[],
                strategies_executed=[],
                error_messages=[],
                metadata={
                    'additional_sources': additional_sources,
                    'selected_folder_ids': selected_folder_ids,
                    'folder_search_enabled': folder_search_enabled
                }
            )
            
            # Step 1: Analyze query — cheap (profession/persona; the sub-query
            # planner LLM was removed). NO retrieval, NO merge, NO relevance
            # scorer here: main chat is PURE AGENTIC. The chat LLM fetches vault
            # docs (list_vault_files → personal_data_tool / execute_code) and
            # enterprise data (dept_* tools) on demand. We pre-fetch NOTHING —
            # only a cheap POINTER (file count) so the agent knows the vault is
            # worth a look. This is the first-token-latency win: the stream
            # starts right after persona, with no pre-stream retrieval round-trips.
            _emit("analyzing_query", "Reading your request")
            state = await self.analyze_query(initial_state)

            # Cheap vault pointer — count only (indexed count_documents, no
            # listing, no LLM). Handed to the agent as "you have N files".
            vault_summary = None
            if use_personal_data and state.get('user_id'):
                try:
                    from services.vault_inventory import count_vault_files
                    vault_summary = await count_vault_files(
                        state['user_id'], selected_folder_ids or [],
                    )
                except Exception as _vc_exc:  # noqa: BLE001
                    logger.warning(f"⚠️ [STREAMING_PREP] vault count failed (non-fatal): {_vc_exc}")
            _emit("context_ready", "Ready")
            
            # Get persona system prompt
            persona_system_prompt = None
            profession = None
            if persona_data:
                try:
                    import sys
                    import os
                    parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
                    if parent_dir not in sys.path:
                        sys.path.insert(0, parent_dir)
                    from persona import generate_persona_system_prompt
                    persona_system_prompt = generate_persona_system_prompt(persona_data)
                    persona_info = persona_data.get('persona', {})
                    profession = persona_info.get('profession', persona_data.get('profession'))
                    logger.info(f"🎯 [STREAMING_PREP] Generated persona prompt for: {profession}")
                except Exception as e:
                    logger.warning(f"🎯 [STREAMING_PREP] Error generating persona prompt: {e}")
            
            # Prepare conversation messages - keep last 5: user queries full, bot replies truncated to 400 words
            conversation_messages = []
            if processed_conversation_history:
                for msg in processed_conversation_history[-5:]:
                    if isinstance(msg, dict):
                        role = msg.get('role', 'user')
                        content = msg.get('content', msg.get('message', msg.get('user_query', ''))).strip()
                        if content:
                            # Truncate bot replies to 400 words, keep user queries full
                            if role != 'user':
                                words = content.split()
                                if len(words) > 400:
                                    content = ' '.join(words[:400]) + "..."
                            conversation_messages.append({
                                'role': role,
                                'content': content
                            })
            
            # PURE AGENTIC: no prefetched context. The chat LLM retrieves on
            # demand via tools, so we never push chunks into the prompt.
            context_chunks = []

            # Grounding signal is POINTER-based, not prefetch-based. The user
            # "has context" if their vault has files OR enterprise is on — the
            # agent will fetch it via tools. We do NOT inject the no-context
            # wrapper merely because nothing was prefetched (there is no
            # prefetch), and we do NOT force internet off an empty-prefetch
            # signal — the agent decides when to call internet_search.
            grounding_payload: Dict[str, Any] = {}
            resolved_temperature: Optional[float] = None
            try:
                _vault_total = int((vault_summary or {}).get('total', 0) or 0)
                _has_sources = _vault_total > 0 or bool(use_enterprise_data)
                effective_internet = bool(enable_internet_search)
                grounding_payload = {
                    "has_context": _has_sources,
                    "agentic": True,
                    "vault_files": _vault_total,
                    "internet_used": effective_internet,
                    "user_enable_internet": enable_internet_search,
                }
                # Only when the user has NO sources at all (empty vault AND no
                # enterprise) do we add the no-context guidance.
                if not _has_sources:
                    try:
                        from prompts.grounding import no_context_wrapper
                        persona_system_prompt = (
                            (persona_system_prompt or "")
                            + "\n\n---\n\n"
                            + no_context_wrapper(internet_available=effective_internet)
                        )
                        logger.info("🛡️ [STREAMING_PREP] No vault/enterprise sources — no-context wrapper added")
                    except Exception as _w_err:  # noqa: BLE001
                        logger.warning(f"⚠️ no-context wrapper injection failed: {_w_err}")
                enable_internet_search = effective_internet
            except Exception as _g_err:  # noqa: BLE001
                logger.warning(f"⚠️ [STREAMING_PREP] Grounding (agentic) error: {_g_err}")

            # 🌡️ Profession-aware temperature
            try:
                from llm.llm_defaults import temperature_for
                resolved_temperature = temperature_for()
            except Exception:
                resolved_temperature = None

            # 📊 Best-effort grounding metrics for streaming path
            try:
                from metrics import record_grounding
                record_grounding(
                    feature='main_chat_stream',
                    chunks_used=len(context_chunks) if context_chunks else 0,
                    context_empty=bool(grounding_payload and not grounding_payload.get('has_context', True)),
                    temperature=resolved_temperature,
                    internet_used=bool(enable_internet_search),
                    internet_reason=str(grounding_payload.get('internet_decision_reason', '')),
                )
            except Exception as _m_err:
                logger.debug(f"record_grounding (stream) skipped: {_m_err}")

            processing_time = time.time() - start_time
            logger.info(f"✅ [STREAMING_PREP] Context ready in {processing_time:.2f}s - {len(context_chunks)} chunks")

            return {
                'context_chunks': context_chunks,
                'merged_context': state.get('merged_context', ''),
                'persona_system_prompt': persona_system_prompt,
                'profession': profession,
                'conversation_messages': conversation_messages,
                'strategies_used': state.get('strategies_executed', []),
                'query_intent': state.get('query_intent'),
                'processing_time': processing_time,
                'metadata': state.get('metadata', {}),
                'grounding': grounding_payload,
                'enable_internet_search': enable_internet_search,
                'temperature': resolved_temperature,
                # Cheap agentic pointer — {structured, unstructured, total} file
                # counts so the chat prompt can tell the agent the vault exists.
                'vault_summary': vault_summary,
            }
            
        except Exception as e:
            logger.error(f"❌ [STREAMING_PREP] Error preparing context: {e}")
            return {
                'context_chunks': [],
                'merged_context': '',
                'persona_system_prompt': None,
                'profession': None,
                'conversation_messages': [],
                'strategies_used': [],
                'error': str(e),
                'processing_time': time.time() - start_time
            }

    async def process_query(
        self,
        query: str,
        user_id: str,
        user_email: Optional[str] = None,
        entity_id: Optional[str] = None,
        entity_name: Optional[str] = None,
        entity_type: Optional[str] = None,
        use_personal_data: bool = True,
        use_enterprise_data: bool = False,
        enterprise_user_info: Optional[Dict[str, Any]] = None,
        org_id: Optional[str] = None,
        dept_id: Optional[str] = None,
        roles: Optional[List[str]] = None,
        conversation_history: Optional[List[Dict]] = None,
        multimodal_attachments: Optional[List[Dict[str, Any]]] = None,
        additional_sources: Optional[Dict[str, Any]] = None,
        model_only_mode: bool = False,
        persona_data: Optional[Dict] = None,
        enable_internet_search: bool = True,
        legal_collection_ids: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """
        Main entry point for processing queries through the agentic RAG system

        ⚠️ LEGACY (non-streaming). Main chat has SHIFTED TO STREAMING:
        process_query_for_streaming() is the live path (called by /query/stream).
        This method runs the full LangGraph including the generate_response node
        and is only reached by the legacy non-streaming /query route. Keep it
        behaviour-aligned with the streaming path until /query is retired; add new
        chat behaviour to the streaming path, not here.

        Args:
            query: User's query text
            user_id: User's device ID
            entity_id: Optional entity ID for filtering
            entity_name: Optional entity name for context
            entity_type: Optional entity type for routing decisions
            use_personal_data: Whether to include personal data
            use_enterprise_data: Whether to include enterprise data
            enterprise_user_info: User identity from middleware (required for enterprise: {"user_id": str, "email": str})
            conversation_history: Previous conversation context
            multimodal_attachments: Raw attachments (images/audio/video) to include in LLM call
            additional_sources: Additional source flags (deep_research, selected_folder_ids for project management, etc.)
            model_only_mode: If True, skip all data retrieval and use direct LLM call
            persona_data: User persona data from the query API
            
        Returns:
            Dict with response and metadata
        """
        start_time = time.time()
        
        try:
            logger.info(f"🚀 Starting agentic RAG processing for query: '{query[:100]}...'")
            
            # 📝 CONVERSATION: Pass through directly — last-5 selection happens downstream
            processed_conversation_history = conversation_history or []

            # Extract additional source flags
            additional_sources = additional_sources or {}
            deep_research = additional_sources.get('deep_research', False)
            query_type = additional_sources.get('query_type', None)
            
            # Extract folder filtering data
            selected_folder_ids = additional_sources.get('selected_folder_ids', [])
            folder_search_enabled = additional_sources.get('folder_search_enabled', False)
            
            # Extract legal collection IDs from additional sources
            legal_collections_from_additional = additional_sources.get('legal_collection_ids', [])
            
            # Log all source configurations
            logger.info(f"📊 Source Configuration:")
            logger.info(f"   🏠 Personal Data: {use_personal_data}")
            logger.info(f"   🏢 Enterprise Data: {use_enterprise_data}")
            logger.info(f"   🔬 Deep Research: {deep_research}")
            logger.info(f"   📋 Query Type: {query_type}")
            logger.info(f"   📁 Folder Filtering: {folder_search_enabled}")
            logger.info(f"   📂 Selected Folders: {selected_folder_ids}")
            logger.info(f"   🤖 Model Only Mode: {model_only_mode}")
            logger.info(f"   ⚖️ Legal Collection IDs: {legal_collection_ids or legal_collections_from_additional}")

            attachments = multimodal_attachments or []
            if attachments:
                attachment_summaries = []
                for att in attachments:
                    name = att.get('name') or att.get('id') or 'unnamed-attachment'
                    mime_type = att.get('mimeType') or att.get('type') or 'application/octet-stream'
                    size_bytes = att.get('size') or 0
                    size_kb = int(size_bytes / 1024) if size_bytes else 0
                    attachment_summaries.append(f"{name} [{mime_type}, ~{size_kb} KB]")
                logger.info(f"📎 Multimodal attachments provided: {attachment_summaries}")
            else:
                logger.info("📎 No multimodal attachments provided")
            
            # � SECURITY: Log enterprise authentication status
            logger.info(f"🏢 [ORCHESTRATOR] Enterprise user_info provided: {bool(enterprise_user_info)}")
            if enterprise_user_info:
                logger.info(f"🏢 [ORCHESTRATOR] Enterprise user_id: {enterprise_user_info.get('user_id')}")
            else:
                logger.info("🏢 [ORCHESTRATOR] No enterprise authentication provided")
            
            # 🚀 FAST PATH: Handle model-only mode immediately without LangGraph processing
            if model_only_mode:
                logger.info("⚡ Model-only mode detected - executing fast path")
                logger.info(f"🌐 [ORCHESTRATOR_FAST_PATH] Internet search: {'ENABLED' if enable_internet_search else 'DISABLED'}")
                
                try:
                    # Import here to avoid circular imports
                    import sys
                    import os
                    # Add parent directory to path so we can import query module
                    parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
                    if parent_dir not in sys.path:
                        sys.path.insert(0, parent_dir)
                    from query import reply
                    
                    # 🎭 PERSONA INTEGRATION: Generate persona-aware system prompt for model-only
                    persona_system_prompt = None
                    profession = None  # Extract profession for collections access control
                    try:
                        if persona_data:
                            from persona import generate_persona_system_prompt
                            persona_system_prompt = generate_persona_system_prompt(persona_data)
                            
                            # Log the actual profession from persona data and extract for collections check
                            persona_info = persona_data.get('persona', {})
                            profession = persona_info.get('profession', persona_data.get('profession'))  # Handle nested and flat structures
                            logger.info(f"🎯 [MODEL-ONLY FAST PATH] Generated persona-aware system prompt for profession: {profession}")
                        else:
                            logger.info("🎯 [MODEL-ONLY FAST PATH] No persona data provided - using default prompt")
                    except ImportError:
                        logger.warning("🎯 [MODEL-ONLY FAST PATH] Persona module not available")
                    except Exception as e:
                        logger.warning(f"🎯 [MODEL-ONLY FAST PATH] Error generating persona prompt: {e}")

                    # Build structured conversation messages (last 5, user full, bot 400w)
                    conversation_messages = []
                    if processed_conversation_history:
                        for msg in processed_conversation_history[-5:]:
                            if isinstance(msg, dict):
                                role = msg.get('role', 'user')
                                content = msg.get('content', msg.get('message', msg.get('user_query', ''))).strip()
                                if content:
                                    if role != 'user':
                                        words = content.split()
                                        if len(words) > 400:
                                            content = ' '.join(words[:400]) + "..."
                                    conversation_messages.append({'role': role, 'content': content})

                    # Choose model: LLM for all queries (text and image)
                    
                    has_image_attachments = any(
                        (att.get('mimeType') or att.get('type') or '').lower().startswith('image/')
                        for att in (attachments or [])
                    )
                    
                    if has_image_attachments:
                        model_to_use = get_default_model()
                        logger.info(f"🖼️ [DEBUG_FAST_PATH] Image attachment detected - using {model_to_use}")
                    else:
                        model_to_use = get_default_model()
                        logger.info(f"📝 [DEBUG_FAST_PATH] Text-only query - using {model_to_use}")
                    
                    # DEBUG: Log before calling reply()
                    logger.info(f"🔍 [DEBUG_FAST_PATH] About to call reply() with:")
                    logger.info(f"  - model: {model_to_use}")
                    logger.info(f"  - query len: {len(query)} chars")
                    logger.info(f"  - conversation_history: {len(conversation_messages)} messages")
                    logger.info(f"  - enable_internet_search: {enable_internet_search}")
                    logger.info(f"  - attachments: {len(attachments) if attachments else 0}")
                    
                    direct_response = reply(
                        query,
                        model_to_use,
                        system=persona_system_prompt,
                        attachments=attachments,
                        enable_internet_search=enable_internet_search,
                        user_id=user_id,
                        user_email=user_email,
                        profession=profession,
                        conversation_history=conversation_messages,  # Structured messages for XAI cache
                        tier="large",
                    )
                    
                    # DEBUG: Log after calling reply()
                    logger.info(f"🔍 [DEBUG_FAST_PATH] reply() returned:")
                    logger.info(f"  - type: {type(direct_response)}")
                    logger.info(f"  - length: {len(direct_response) if direct_response else 0} chars")
                    logger.info(f"  - is empty: {not direct_response}")
                    if direct_response:
                        logger.info(f"  - preview: {direct_response[:200]}...")
                    else:
                        logger.warning("⚠️ [DEBUG_FAST_PATH] reply() returned empty response!")
                    
                    # Formatting is now handled in query.py reply_llm (llm_oss) based on actual internet search usage
                    logger.info("⚡ [ORCHESTRATOR] Formatting handled in query.py - using response as-is")
                    final_response = direct_response
                    
                    processing_time = time.time() - start_time
                    
                    # Return fast response - UI parses SOURCES from response text
                    fast_response_data = {
                        "response": final_response,  # Use formatted response when internet enabled, raw otherwise
                        "strategies_used": ["model_only"],
                        "processing_time": processing_time,
                        "metadata": {
                            "total_sources": 0,
                            "agentic_rag": False,
                            "model_only_mode": True,
                            "fast_path_used": True,
                            "multi_hop_executed": False,
                            "persona_used": bool(persona_data),
                            "persona_profession": persona_data.get('persona', {}).get('profession', 'None') if persona_data else 'None',
                            "error_messages": []
                        }
                    }
                    
                    logger.info(f"⚡ Model-only fast path complete in {processing_time:.2f}s")
                    if persona_data:
                        logger.info(f"🎭 Applied persona-aware prompts for {persona_data.get('persona', {}).get('profession', 'Unknown')}")
                    
                    return fast_response_data
                    
                except Exception as e:
                    logger.error(f"❌ Model-only fast path failed: {e}")
                    # Fall back to normal processing
                    logger.info("🔄 Falling back to normal LangGraph processing")
            
            # Initialize state
            initial_state = QueryState(
                query=query,
                user_id=user_id,
                user_email=user_email,
                entity_id=entity_id,
                entity_name=entity_name,
                entity_type=entity_type,
                use_personal_data=use_personal_data,
                use_enterprise_data=use_enterprise_data,
                org_id=org_id,
                dept_id=dept_id,
                roles=roles or ["user"],
                use_saas_data=True,
                enterprise_user_info=enterprise_user_info,
                conversation_history=processed_conversation_history,
                multimodal_attachments=attachments,
                persona_data=persona_data,
                enable_internet_search=enable_internet_search,
                legal_collection_ids=legal_collection_ids or legal_collections_from_additional,
                personal_contexts=[],
                enterprise_contexts=[],
                entity_contexts=[],
                kg_contexts=[],  # Initialize knowledge graph contexts
                saas_contexts=[],  # NEW: Initialize SaaS contexts (from Milvus saas collection)
                strategies_executed=[],
                error_messages=[],
                metadata={
                    'additional_sources': additional_sources,
                    'deep_research': deep_research,
                    'query_type': query_type,
                    'model_only_mode': model_only_mode,
                    'selected_folder_ids': selected_folder_ids,  # Project management will use this
                    'folder_search_enabled': folder_search_enabled
                }
            )
            
            # Run the graph
            result = await self.graph.ainvoke(initial_state)
            
            processing_time = time.time() - start_time
            
            # Get final response with SOURCES section intact (UI parses it directly)
            final_response = result.get('final_response', 'No response generated')
            
            # Formatting is now handled in query.py reply_llm (llm_oss) based on actual internet search usage
            # No need to format here in orchestrator
            logger.info("⚡ [ORCHESTRATOR] Formatting handled in query.py - using response as-is")
            formatted_response = final_response
            
            # Prepare final response - UI parses SOURCES section directly from response text
            response_data = {
                "response": formatted_response,  # Use formatted response instead of raw
                "strategies_used": result.get('strategies_executed', []),
                "processing_time": processing_time,
                "metadata": {
                    "agentic_rag": True,
                    "multi_hop_executed": bool(result.get('multi_hop_result')),
                    "kg_retrieval_executed": bool(result.get('kg_contexts', [])),
                    "kg_contexts_count": len(result.get('kg_contexts', [])),
                    "query_intent": result.get('query_intent').__dict__ if result.get('query_intent') else None,
                    "error_messages": result.get('error_messages', []),
                    **result.get('metadata', {})
                }
            }
            
            logger.info(f"✅ Agentic RAG processing complete in {processing_time:.2f}s")
            logger.info(f"📊 Strategies executed: {result.get('strategies_executed', [])}")
            if result.get('kg_contexts'):
                logger.info(f"🧠 Knowledge graph contexts: {len(result.get('kg_contexts', []))}")
            
            return response_data
            
        except Exception as e:
            processing_time = time.time() - start_time
            logger.error(f"❌ Agentic RAG processing failed after {processing_time:.2f}s: {e}")
            
            return {
                "response": f"An error occurred during query processing: {str(e)}",
                "strategies_used": [],
                "processing_time": processing_time,
                "metadata": {
                    "error": str(e),
                    "fallback_used": True,
                    "agentic_rag": False,
                    "total_sources": 0
                }
            }
    
    # Note: Old _extract_citation_metadata method removed - it incorrectly extracted from contexts
    # Citations are now properly extracted from LLM responses only in _extract_unified_citations_for_api()
