#!/usr/bin/env bash
# Guided first-run setup:
#   1. .env with fresh secrets
#   2. AI provider (required — generation needs a model)
#   3. bring the stack up
#
# Re-runnable: reads and updates the existing .env, so run it again to change
# a key. Prereqs: docker, curl, openssl.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/.env"

b()  { printf '\033[1m%s\033[0m' "$1"; }
hr() { printf '\n------------------------------------------------------------\n'; }
ask() {
  local q="$1" def="${2:-}" ans
  if [ -n "$def" ]; then printf '%s [%s]: ' "$q" "$def" >&2; else printf '%s: ' "$q" >&2; fi
  read -r ans || true; printf '%s' "${ans:-$def}"
}
ask_secret() { local q="$1" ans; printf '%s: ' "$q" >&2; read -rs ans || true; printf '\n' >&2; printf '%s' "$ans"; }
yes_no() { local q="$1" def="${2:-y}" a; a="$(ask "$q (y/n)" "$def")"; case "$a" in y|Y|yes|YES) return 0;; *) return 1;; esac; }

rand()  { openssl rand -hex "$1" 2>/dev/null || head -c "$((${1}*2))" /dev/urandom | od -An -tx1 | tr -d ' \n'; }
getkv() { grep -E "^$1=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- ; }
setkv() {
  local k="$1" v="$2"
  if grep -qE "^$k=" "$ENV_FILE" 2>/dev/null; then
    awk -v k="$k" -v v="$v" 'BEGIN{FS="="} $1==k{print k"="v; next} {print}' "$ENV_FILE" > "$ENV_FILE.tmp" && mv "$ENV_FILE.tmp" "$ENV_FILE"
  else
    printf '%s=%s\n' "$k" "$v" >> "$ENV_FILE"
  fi
}

clear 2>/dev/null || true
echo "$(b "citra-decks — setup wizard")"
echo "Sovereign presentations, visual reports and long-form documents."

# -- 1. .env ------------------------------------------------------------------
hr; echo "$(b "Step 1/3 — environment file")"
if [ -f "$ENV_FILE" ]; then
  echo "Found an existing .env — keeping it (values you set are preserved)."
else
  echo "Generating .env from .env.example with fresh random secrets..."
  cp .env.example "$ENV_FILE"
  MONGO_PW="$(rand 16)"
  setkv MONGODB_PASSWORD "$MONGO_PW"
  setkv MONGODB_CONN_STRING "mongodb://root:${MONGO_PW}@mongodb:27017/?authSource=admin&replicaSet=rs0"
  setkv JWT_SECRET "$(rand 48)"
  setkv CONNECTION_ENCRYPTION_KEY "$(rand 32)"
  echo "  [ok] secrets generated (Mongo password, JWT secret, encryption key)"
fi

# -- 2. AI provider -------------------------------------------------------------
# ONE provider, deliberately. A single OpenRouter key covers reasoning,
# embeddings and vision, so there is one key to paste and one thing that can be
# wrong. Offering four providers previously set only the LLM_* vars — a user who
# picked OpenAI finished the wizard with EMBEDDING_BASE_URL still empty, so the
# composers came up unable to ground anything in their documents, silently.
# Every default below is open-weights and swappable by editing .env.
hr; echo "$(b "Step 2/4 — AI provider (required)")"
echo "The composers call an LLM to draft, an embedding model to ground that"
echo "draft in your documents, and a vision model to read images. One"
echo "OpenRouter key covers all three."
echo
echo "  Get a key: $(b "https://openrouter.ai/keys")"
key="$(ask_secret "Paste your OpenRouter API key (input hidden)")"

if [ -z "$key" ]; then
  echo
  echo "  [FAIL] no key entered. Presentation/printable generation cannot" >&2
  echo "         produce anything without a model. Re-run once you have a key." >&2
  exit 1
fi

base="https://openrouter.ai/api/v1"
model="deepseek/deepseek-v4-pro"
setkv LLM_LARGE_BASE_URL  "$base"; setkv LLM_LARGE_MODEL  "$model"; setkv LLM_LARGE_API_KEY  "$key"
setkv LLM_MEDIUM_BASE_URL "$base"; setkv LLM_MEDIUM_MODEL "$model"; setkv LLM_MEDIUM_API_KEY "$key"
setkv LLM_SMALL_BASE_URL  "$base"; setkv LLM_SMALL_MODEL  "$model"; setkv LLM_SMALL_API_KEY  "$key"
# Slide and report layout stays pinned to GLM-5.1 — it produces the best
# structure of the models tested, and OpenRouter carries it.
setkv PRESENTATION_LLM_MODEL "z-ai/glm-5.1"
setkv PRINTABLE_LLM_MODEL    "z-ai/glm-5.1"
# Grounding. Without these the composers still draft, but from nothing but the
# prompt — the one thing this product exists not to do.
setkv EMBEDDING_BASE_URL  "$base"
setkv EMBEDDING_MODEL     "baai/bge-m3"
setkv EMBEDDING_DIMENSION "768"
setkv EMBEDDING_API_KEY   "$key"
setkv VISION_BASE_URL "$base"
setkv VISION_MODEL    "qwen/qwen3-vl-32b-instruct"
setkv VISION_API_KEY  "$key"
echo "  [ok] one key configured for drafting, grounding and vision"

# -- 3. Image generation ----------------------------------------------------------
hr; echo "$(b "Step 3/4 — image generation (optional)")"
echo "Slide and cover imagery is generated by Runware, not OpenRouter, so it"
echo "needs its own key. Skip this and the composers simply use no generated"
echo "imagery."
if yes_no "Add a Runware key?" "n"; then
  rw="$(ask_secret "Runware API key")"
  if [ -n "$rw" ]; then
    setkv IMAGE_GEN_PROVIDER "runware"
    setkv IMAGE_GEN_API_KEY  "$rw"
    echo "  [ok] Runware configured"
  fi
fi

# -- 4. Bring it up ---------------------------------------------------------------
hr; echo "$(b "Step 4/4 — bring up the stack")"
if yes_no "Run setup now (data stores)?" "y"; then
  "$REPO_ROOT/scripts/quickstart/setup.sh"
fi
if yes_no "Start all services?" "y"; then
  "$REPO_ROOT/scripts/quickstart/start.sh"
fi

hr
echo "$(b "Done.")  Open  http://localhost:8094  and create your first account."
echo "Re-run this wizard any time to change keys:  ./scripts/quickstart/wizard.sh"
