// Load environment variables using vault_env_loader
const { loadEnvironmentVariables } = require('./vault_env_loader');

(async () => {
    try {
        await loadEnvironmentVariables();
    } catch (error) {
        console.error('❌ Failed to load environment variables:', error.message);
        process.exit(1);
    }

const WebSocket = require('ws');
const http = require('http');
const jwt = require('jsonwebtoken');
const setupWSConnection = require('y-websocket/bin/utils').setupWSConnection;
const LeveldbPersistence = require('y-leveldb').LeveldbPersistence;
const Y = require('yjs');

// Kill switch: real-time collaboration is DISABLED platform-wide. While
// disabled the server stays up to answer /health (so orchestration doesn't
// flap) but refuses every WebSocket upgrade. Set COLLABORATION_ENABLED=true
// to re-enable; the Citra-UI hooks must be re-enabled too.
const COLLABORATION_ENABLED = process.env.COLLABORATION_ENABLED === 'true';

// Configuration
const PORT = process.env.PORT || 1234;
const PERSISTENCE_DIR = process.env.PERSISTENCE_DIR || './y-leveldb-storage';
const JWT_SECRET = process.env.JWT_SECRET;
// Required (RULE #1): no localhost fallback — a missing auth-service URL must
// fail loud, not silently point at a dev host. Set AUTH_SERVICE_URL in .env
// (local dev) or Vault (prod).
const AUTH_SERVICE_URL = process.env.AUTH_SERVICE_URL;
if (!AUTH_SERVICE_URL) {
    console.error('❌ AUTH_SERVICE_URL not configured — refusing to start on a localhost fallback.');
    process.exit(1);
}
const IDLE_TIMEOUT_MS = 30 * 60 * 1000; // 30 minutes
const MAX_CONNECTIONS_PER_DOC = 10;

if (!JWT_SECRET && process.env.NODE_ENV === 'production') {
    console.error('❌ JWT_SECRET not configured! Server will reject all connections in production.');
}

// Persistence (LevelDB for simplicity and speed)
const ldb = new LeveldbPersistence(PERSISTENCE_DIR);

// Track active documents with metadata
const docMetadata = new Map(); // docName -> { lastActivity, connectionCount }

/**
 * Persist document updates to LevelDB
 */
const persistence = {
    bindState: async (docName, ydoc) => {
        const persistedYdoc = await ldb.getYDoc(docName);
        const newUpdates = Y.encodeStateAsUpdate(ydoc);
        ldb.storeUpdate(docName, newUpdates);
        Y.applyUpdate(ydoc, Y.encodeStateAsUpdate(persistedYdoc));

        ydoc.on('update', update => {
            ldb.storeUpdate(docName, update);
            // Update activity timestamp
            if (docMetadata.has(docName)) {
                docMetadata.get(docName).lastActivity = Date.now();
            }
        });
    },
    writeState: async (docName, ydoc) => {
        // This is called when document is potentially destroyed or periodically
        // With y-leveldb, we primarily use the listener approach above
    }
};

// Create HTTP Server
const server = http.createServer((request, response) => {
    if (request.url === '/health') {
        response.writeHead(200, { 'Content-Type': 'application/json' });
        response.end(JSON.stringify({ status: 'ok', enabled: COLLABORATION_ENABLED, activeRooms: docMetadata.size }));
        return;
    }
    if (request.url === '/stats') {
        const stats = {
            activeRooms: docMetadata.size,
            rooms: Array.from(docMetadata.entries()).map(([name, meta]) => ({
                name,
                connections: meta.connectionCount,
                idleMinutes: Math.round((Date.now() - meta.lastActivity) / 60000)
            }))
        };
        response.writeHead(200, { 'Content-Type': 'application/json' });
        response.end(JSON.stringify(stats));
        return;
    }
    response.writeHead(200, { 'Content-Type': 'text/plain' });
    response.end('Citra AI Collaboration Service');
});

// Create WebSocket Server
const wss = new WebSocket.Server({ noServer: true });

/**
 * Verify JWT token using same secret as Citra Service
 * Token is generated by user-service-VM after Google auth
 * Same JWT_SECRET is shared across all services (.env)
 */
function verifyCollabToken(token) {
    if (!token) return { valid: false, error: 'No token provided' };

    // Require JWT_SECRET in ALL environments
    if (!JWT_SECRET) {
        return { valid: false, error: 'JWT_SECRET not configured' };
    }

    try {
        // Decode using same algorithm as Citra Service (HS256)
        const decoded = jwt.verify(token, JWT_SECRET, { algorithms: ['HS256'] });

        // Validate required claims (same as auth_middleware.py)
        if (!decoded.user_id || !decoded.email || !decoded.exp) {
            return { valid: false, error: 'Missing required claims' };
        }

        return { valid: true, user: decoded };
    } catch (error) {
        if (error.name === 'TokenExpiredError') {
            return { valid: false, error: 'Token expired' };
        }
        return { valid: false, error: error.message };
    }
}

wss.on('connection', (conn, req, { docName = req.url.slice(1) } = {}) => {
    console.log(`[Collab] Connection established for doc: ${docName}`);

    // Initialize or update doc metadata
    if (!docMetadata.has(docName)) {
        docMetadata.set(docName, { lastActivity: Date.now(), connectionCount: 0 });
    }
    const meta = docMetadata.get(docName);
    meta.connectionCount++;
    meta.lastActivity = Date.now();

    // Setup Yjs connection
    setupWSConnection(conn, req, {
        docName,
        gc: true
    });

    // Handle disconnect
    conn.on('close', () => {
        if (docMetadata.has(docName)) {
            const meta = docMetadata.get(docName);
            meta.connectionCount = Math.max(0, meta.connectionCount - 1);
            console.log(`[Collab] Connection closed for ${docName}, remaining: ${meta.connectionCount}`);
        }
    });
});

// Upgrade handle with authentication
server.on('upgrade', (request, socket, head) => {
    // Kill switch: refuse all collaboration sessions while disabled.
    if (!COLLABORATION_ENABLED) {
        console.warn('[Collab] Rejecting upgrade — collaboration is disabled (COLLABORATION_ENABLED!=true)');
        socket.write('HTTP/1.1 503 Service Unavailable\r\n\r\n');
        socket.destroy();
        return;
    }

    // Parsing parameters from URL (e.g., /presentation-123?token=xyz)
    const url = new URL(request.url, `http://${request.headers.host}`);
    const docName = url.pathname.slice(1); // remove leading slash
    const token = url.searchParams.get('token');

    // Check connection limits
    if (docMetadata.has(docName)) {
        const meta = docMetadata.get(docName);
        if (meta.connectionCount >= MAX_CONNECTIONS_PER_DOC) {
            console.warn(`[Collab] Connection limit reached for ${docName}`);
            socket.write('HTTP/1.1 503 Service Unavailable\r\n\r\n');
            socket.destroy();
            return;
        }
    }

    // Verify token using same JWT_SECRET as Citra Service
    const authResult = verifyCollabToken(token);

    if (!authResult.valid) {
        // Reject invalid tokens in ALL environments
        console.warn(`[Collab] Authentication failed for ${docName}: ${authResult.error}`);
        socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');
        socket.destroy();
        return;
    }

    console.log(`[Collab] Authenticated user ${authResult.user?.email} for ${docName}`);

    // Upgrade to WebSocket
    wss.handleUpgrade(request, socket, head, (ws) => {
        wss.emit('connection', ws, request, { docName });
    });
});

// Custom Persistence binding middleware for y-websocket utils
const utils = require('y-websocket/bin/utils');

utils.setPersistence({
    bindState: async (docName, ydoc) => {
        await persistence.bindState(docName, ydoc);
    },
    writeState: async (docName, ydoc) => {
        await persistence.writeState(docName, ydoc);
    }
});

/**
 * Idle Room Eviction
 * Runs every 5 minutes to clean up inactive rooms
 */
const docs = utils.docs;

setInterval(() => {
    const now = Date.now();
    let evictedCount = 0;

    docMetadata.forEach((meta, docName) => {
        // Only evict if no connections and idle for IDLE_TIMEOUT_MS
        if (meta.connectionCount === 0 && (now - meta.lastActivity) > IDLE_TIMEOUT_MS) {
            console.log(`[Collab] Evicting idle room: ${docName} (idle for ${Math.round((now - meta.lastActivity) / 60000)} minutes)`);

            // Destroy Yjs document if it exists
            if (docs.has(docName)) {
                const doc = docs.get(docName);
                doc.destroy();
                docs.delete(docName);
            }

            docMetadata.delete(docName);
            evictedCount++;
        }
    });

    if (evictedCount > 0) {
        console.log(`[Collab] Evicted ${evictedCount} idle room(s), ${docMetadata.size} active`);
    }
}, 5 * 60 * 1000); // Every 5 minutes

// Start Server
server.listen(PORT, () => {
    console.log(`
  🚀 Collaboration Service running on port ${PORT}
  ${COLLABORATION_ENABLED ? '✅ Collaboration: ENABLED' : '⛔ Collaboration: DISABLED — refusing all WebSocket upgrades (set COLLABORATION_ENABLED=true to re-enable)'}
  📁 Persistence: ${PERSISTENCE_DIR}
  🔐 Auth Service: ${AUTH_SERVICE_URL}
  ⏱️  Idle Timeout: ${IDLE_TIMEOUT_MS / 60000} minutes
  👥 Max Connections/Doc: ${MAX_CONNECTIONS_PER_DOC}
  `);
});
})();
