#!/usr/bin/env python3
# Copyright (c) 2026 Trustedwear Tech Private Limited (https://citra-ai.com)
# Author: Rohit Kumar Chandan
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at http://www.apache.org/licenses/LICENSE-2.0

"""
Milvus Hybrid Search Schema Setup Script

Creates optimal collection schema for hybrid search with:
- Dense vectors (LLM 768d, COSINE similarity)
- Sparse vectors (BM25, Inner Product)
- Dynamic metadata fields
- Optimized indexes (AUTOINDEX + SPARSE_INVERTED_INDEX)

Best Practices:
1. INT64 primary keys for performance
2. COSINE metric for normalized embeddings
3. IP metric for BM25 scores
4. AUTOINDEX for automatic optimization
5. Dynamic fields for flexible metadata

Usage:
    python scripts/setup_milvus_schema.py              # Create schema
    python scripts/setup_milvus_schema.py --check      # Check only
    python scripts/setup_milvus_schema.py --force      # Force recreate
    python scripts/setup_milvus_schema.py --validate   # Validate schema
"""

import sys
import os
import argparse
import logging
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from pymilvus import (
    connections,
    utility,
    FieldSchema,
    CollectionSchema,
    DataType,
    Collection,
    Function,
    FunctionType
)

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def get_config():
    """Load Milvus configuration from environment"""
    from dotenv import load_dotenv
    load_dotenv()
    
    from config.milvus_config import (
        get_collection_name,
        get_milvus_uri,
        get_milvus_api_key,
        get_dense_vector_dim,
        is_hybrid_search_enabled
    )
    
    return {
        'collection_name': get_collection_name(),
        'uri': get_milvus_uri(),
        'token': get_milvus_api_key(),
        'dense_dim': get_dense_vector_dim(),
        'hybrid_enabled': is_hybrid_search_enabled()
    }


def connect_milvus(config):
    """Connect to Milvus using pymilvus low-level API"""
    logger.info(f"🔌 Connecting to Milvus...")
    logger.info(f"   URI: {config['uri']}")
    
    connections.connect(
        alias="default",
        uri=config['uri'],
        token=config['token']
    )
    logger.info("✅ Connected to Milvus")


def create_optimal_schema(config):
    """
    Create optimal collection schema for hybrid search with SERVER-SIDE BM25.
    
    Schema Best Practices (Milvus 2.4+ / Zilliz Cloud):
    1. Primary Key: INT64 (faster than VARCHAR)
    2. Dense Vector: FLOAT_VECTOR with COSINE metric
    3. Text Field: VARCHAR with enable_analyzer=True (for BM25 tokenization)
    4. Sparse Vector: SPARSE_FLOAT_VECTOR (auto-generated by BM25 Function)
    5. Dynamic Fields: Enabled for flexible metadata
    6. Built-in BM25 Function: Server-side sparse vector generation (like Pinecone)
    """
    
    collection_name = config['collection_name']
    dense_dim = config['dense_dim']
    hybrid_enabled = config['hybrid_enabled']
    
    logger.info(f"📋 Creating schema for: {collection_name}")
    logger.info(f"   Dense dimensions: {dense_dim}")
    logger.info(f"   Hybrid search: {hybrid_enabled} (server-side BM25)")
    
    # Define fields
    fields = [
        # Primary key - INT64 for optimal performance
        FieldSchema(
            name="primary_key",
            dtype=DataType.INT64,
            is_primary=True,
            auto_id=False,
            description="Primary key (hash of chunk_id)"
        ),
        
        # Original UUID for reference
        FieldSchema(
            name="chunk_id",
            dtype=DataType.VARCHAR,
            max_length=100,
            description="Original UUID chunk identifier"
        ),
        
        # Dense vector - embeddings (768d)
        FieldSchema(
            name="dense_vector",
            dtype=DataType.FLOAT_VECTOR,
            dim=dense_dim,
            description="Dense embeddings from LLM for semantic search"
        ),
        
        # User identifier for filtering
        FieldSchema(
            name="user_id",
            dtype=DataType.VARCHAR,
            max_length=100,
            description="User/device identifier for multi-tenancy"
        ),
        
        # Document identifier for grouping
        FieldSchema(
            name="document_id",
            dtype=DataType.VARCHAR,
            max_length=100,
            description="Parent document identifier"
        ),
        
        # Folder identifier for personal data filtering
        FieldSchema(
            name="folder_id",
            dtype=DataType.VARCHAR,
            max_length=100,
            description="Folder identifier for organizing personal documents"
        ),
        
        # Entity identifier for enterprise data filtering
        FieldSchema(
            name="entity_id",
            dtype=DataType.VARCHAR,
            max_length=100,
            description="Entity identifier for enterprise data isolation (e.g., company ID)"
        ),
        
        # Text content - with analyzer enabled for server-side BM25
        FieldSchema(
            name="text",
            dtype=DataType.VARCHAR,
            max_length=65535,  # Maximum supported
            enable_analyzer=hybrid_enabled,  # CRITICAL: Enables BM25 tokenization
            description="Chunk text content (tokenized for BM25 if hybrid enabled)"
        ),
        
        # Chunk metadata
        FieldSchema(
            name="chunk_index",
            dtype=DataType.INT64,
            description="Position of chunk in document"
        ),
        
        FieldSchema(
            name="total_chunks",
            dtype=DataType.INT64,
            description="Total chunks in document"
        ),
        
        # Timestamps
        FieldSchema(
            name="created_at",
            dtype=DataType.INT64,
            description="Creation timestamp (epoch ms)"
        )
    ]
    
    # Add sparse vector field if hybrid search is enabled (for server-side BM25)
    if hybrid_enabled:
        logger.info("   + Adding sparse vector field (server-side BM25)")
        fields.append(
            FieldSchema(
                name="sparse_vector",
                dtype=DataType.SPARSE_FLOAT_VECTOR,
                description="Sparse embeddings AUTO-GENERATED by Zilliz Cloud BM25"
            )
        )
    
    # Create collection schema with dynamic fields
    schema = CollectionSchema(
        fields=fields,
        description=f"Hybrid RAG with dense + SERVER-SIDE BM25 sparse (Environment: {collection_name})",
        enable_dynamic_field=True  # Allow arbitrary metadata
    )
    
    # Add built-in BM25 Function for server-side sparse vector generation
    if hybrid_enabled:
        logger.info("   + Adding server-side BM25 Function (like Pinecone sparse)")
        bm25_function = Function(
            name="text_bm25_embedding",
            input_field_names=["text"],  # Text field to tokenize
            output_field_names=["sparse_vector"],  # Auto-generated sparse vectors
            function_type=FunctionType.BM25
        )
        schema.add_function(bm25_function)
        logger.info("     - Function: text_bm25_embedding")
        logger.info("     - Input: text (auto-tokenized)")
        logger.info("     - Output: sparse_vector (auto-generated)")
        logger.info("     ✅ No fitting required! BM25 computed by Zilliz Cloud server")
    
    logger.info(f"✅ Schema created with {len(fields)} fields")
    logger.info(f"   Dynamic fields: enabled")
    logger.info(f"   Server-side BM25: {hybrid_enabled}")
    
    return schema


def create_optimal_indexes(collection, config):
    """
    Create optimal indexes for hybrid search with server-side BM25.
    
    Index Best Practices:
    1. Dense Vector: AUTOINDEX (auto-optimizes based on data)
       - Metric: COSINE (best for normalized embeddings)
    2. Sparse Vector: AUTOINDEX with BM25 metric (for server-side BM25)
       - Metric: BM25 (required for full-text search)
       - Zilliz Cloud automatically manages BM25 parameters
    3. Scalar Fields: Optional indexes for filtering
    """
    
    hybrid_enabled = config['hybrid_enabled']
    
    logger.info("🔍 Creating indexes...")
    
    # Dense vector index - AUTOINDEX with COSINE
    logger.info("   + Dense vector index (AUTOINDEX, COSINE)")
    index_params_dense = {
        "metric_type": "COSINE",
        "index_type": "AUTOINDEX",
        "params": {}
    }
    collection.create_index(
        field_name="dense_vector",
        index_params=index_params_dense,
        index_name="dense_index"
    )
    
    # Sparse vector index - AUTOINDEX with BM25 metric (server-side)
    if hybrid_enabled:
        logger.info("   + Sparse vector index (AUTOINDEX, BM25 - server-side)")
        index_params_sparse = {
            "metric_type": "BM25",  # CRITICAL: Use BM25 metric for server-side function
            "index_type": "AUTOINDEX",  # Let Zilliz Cloud optimize
            "params": {}
        }
        collection.create_index(
            field_name="sparse_vector",
            index_params=index_params_sparse,
            index_name="sparse_index"
        )
        logger.info("     ✅ Server-side BM25 (no client fitting needed!)")
    
    # Scalar indexes for common filters
    logger.info("   + Scalar field indexes for filtering")
    for field_name in ["user_id", "document_id", "folder_id", "entity_id"]:
        try:
            collection.create_index(
                field_name=field_name,
                index_name=f"{field_name}_index"
            )
            logger.info(f"     - {field_name}: indexed")
        except Exception as e:
            logger.warning(f"     - {field_name}: {e}")
    
    logger.info("✅ Indexes created successfully")
    logger.info("   - Dense: COSINE similarity")
    logger.info("   - Sparse: Server-side BM25 (like Pinecone)")
    logger.info("   - Filters: user_id, document_id, folder_id, entity_id")


def collection_exists(config):
    """Check if collection exists"""
    collection_name = config['collection_name']
    return utility.has_collection(collection_name)


def get_collection_info(config):
    """Get detailed collection information"""
    collection_name = config['collection_name']
    
    if not collection_exists(config):
        return None
    
    collection = Collection(name=collection_name)
    
    info = {
        'name': collection.name,
        'description': collection.description,
        'num_entities': collection.num_entities,
        'fields': []
    }
    
    for field in collection.schema.fields:
        field_info = {
            'name': field.name,
            'type': str(field.dtype),
            'is_primary': field.is_primary,
            'auto_id': field.auto_id
        }
        
        if field.dtype in [DataType.FLOAT_VECTOR, DataType.BINARY_VECTOR]:
            field_info['dim'] = field.params.get('dim', 'N/A')
        
        if field.dtype == DataType.VARCHAR:
            field_info['max_length'] = field.params.get('max_length', 'N/A')
        
        info['fields'].append(field_info)
    
    # Get indexes
    info['indexes'] = []
    try:
        for field in collection.schema.fields:
            if field.name in ["dense_vector", "sparse_vector", "user_id", "document_id"]:
                idx = collection.index(field.name)
                if idx:
                    info['indexes'].append({
                        'field': field.name,
                        'type': idx.params.get('index_type', 'N/A'),
                        'metric': idx.params.get('metric_type', 'N/A')
                    })
    except Exception as e:
        logger.warning(f"Could not retrieve indexes: {e}")
    
    return info


def create_collection(config, force_recreate=False):
    """Create collection with optimal schema"""
    collection_name = config['collection_name']
    
    # Check if exists
    exists = collection_exists(config)
    
    if exists and not force_recreate:
        logger.warning(f"⚠️  Collection '{collection_name}' already exists")
        logger.info("   Use --force to recreate (⚠️  DELETES ALL DATA)")
        return False
    
    if exists and force_recreate:
        logger.warning(f"🗑️  Dropping existing collection '{collection_name}'...")
        utility.drop_collection(collection_name)
        logger.info("✅ Existing collection dropped")
    
    # Create schema
    schema = create_optimal_schema(config)
    
    # Create collection
    logger.info(f"🚀 Creating collection '{collection_name}'...")
    collection = Collection(
        name=collection_name,
        schema=schema,
        using='default'
    )
    logger.info(f"✅ Collection created successfully")
    
    # Create indexes
    create_optimal_indexes(collection, config)
    
    # Load collection
    logger.info("📥 Loading collection into memory...")
    collection.load()
    logger.info("✅ Collection loaded and ready")
    
    return True


def validate_schema(config):
    """Validate existing collection schema"""
    collection_name = config['collection_name']
    
    if not collection_exists(config):
        logger.error(f"❌ Collection '{collection_name}' does not exist")
        return False
    
    collection = Collection(name=collection_name)
    
    # Check required fields (including new folder_id and entity_id)
    field_names = [f.name for f in collection.schema.fields]
    required_fields = ["primary_key", "chunk_id", "dense_vector", "user_id", "document_id", "folder_id", "entity_id", "text"]
    
    missing = [f for f in required_fields if f not in field_names]
    if missing:
        logger.error(f"❌ Missing required fields: {missing}")
        return False
    
    # Check dense vector dimension
    dense_field = next((f for f in collection.schema.fields if f.name == "dense_vector"), None)
    if dense_field:
        dim = dense_field.params.get('dim', 0)
        if dim != config['dense_dim']:
            logger.error(f"❌ Dense vector dimension mismatch: {dim} != {config['dense_dim']}")
            return False
    
    # Check sparse vector if hybrid enabled
    if config['hybrid_enabled']:
        if "sparse_vector" not in field_names:
            logger.error(f"❌ Hybrid search enabled but sparse_vector field missing")
            return False
    
    logger.info("✅ Schema validation passed")
    return True


def main():
    parser = argparse.ArgumentParser(
        description='Setup Milvus hybrid search schema',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Create schema (safe - won't delete existing)
  python scripts/setup_milvus_schema.py

  # Check existing schema
  python scripts/setup_milvus_schema.py --check

  # Force recreate (⚠️  DELETES ALL DATA)
  python scripts/setup_milvus_schema.py --force

  # Validate schema
  python scripts/setup_milvus_schema.py --validate

Environment Variables (.env):
  MILVUS_URI              - Zilliz Cloud endpoint
  MILVUS_API_KEY          - API key for authentication
  MILVUS_COLLECTION       - Collection name (e.g., dev)
  DENSE_VECTOR_DIM        - Dense vector dimension (default: 768)
  HYBRID_SEARCH_ENABLED   - Enable sparse vectors (default: true)
        """
    )
    
    parser.add_argument(
        '--check',
        action='store_true',
        help='Check if collection exists and show detailed info'
    )
    
    parser.add_argument(
        '--force',
        action='store_true',
        help='Force recreate collection (⚠️  DELETES ALL DATA)'
    )
    
    parser.add_argument(
        '--validate',
        action='store_true',
        help='Validate existing schema matches expected configuration'
    )
    
    args = parser.parse_args()
    
    try:
        # Load configuration
        config = get_config()
        
        logger.info("=" * 70)
        logger.info("🔧 Milvus Hybrid Search Schema Setup")
        logger.info("=" * 70)
        logger.info(f"Collection: {config['collection_name']}")
        logger.info(f"Dense dim: {config['dense_dim']}")
        logger.info(f"Hybrid search: {config['hybrid_enabled']}")
        logger.info("=" * 70)
        
        # Connect to Milvus
        connect_milvus(config)
        
        # Check mode - show collection info
        if args.check:
            logger.info("\n🔍 Checking collection status...")
            
            if not collection_exists(config):
                logger.info("❌ Collection does not exist")
                logger.info("💡 Run without --check to create it")
                return 1
            
            logger.info("✅ Collection exists")
            
            info = get_collection_info(config)
            logger.info(f"\n📊 Collection Details:")
            logger.info(f"   Name: {info['name']}")
            logger.info(f"   Description: {info['description']}")
            logger.info(f"   Entities: {info['num_entities']:,}")
            logger.info(f"\n   Fields ({len(info['fields'])}):")
            
            for field in info['fields']:
                primary = " (PRIMARY)" if field.get('is_primary') else ""
                dim_info = f" [{field.get('dim')}d]" if 'dim' in field else ""
                max_len = f" [max:{field.get('max_length')}]" if 'max_length' in field else ""
                logger.info(f"     - {field['name']}: {field['type']}{dim_info}{max_len}{primary}")
            
            if info['indexes']:
                logger.info(f"\n   Indexes ({len(info['indexes'])}):")
                for idx in info['indexes']:
                    logger.info(f"     - {idx['field']}: {idx['type']} ({idx['metric']})")
            
            return 0
        
        # Validate mode
        if args.validate:
            logger.info("\n🔍 Validating schema...")
            
            is_valid = validate_schema(config)
            
            if is_valid:
                logger.info("✅ Schema validation passed - collection is correctly configured")
                return 0
            else:
                logger.error("❌ Schema validation failed")
                logger.info("💡 Run with --force to recreate with correct schema")
                return 1
        
        # Force recreate mode
        if args.force:
            logger.warning("\n⚠️  FORCE RECREATE MODE")
            logger.warning("⚠️  This will DELETE ALL DATA in the collection!")
            logger.warning(f"⚠️  Collection: {config['collection_name']}")
            
            # Confirmation prompt
            response = input("\n❓ Type 'DELETE' to confirm: ")
            if response != 'DELETE':
                logger.info("❌ Aborted - wrong confirmation")
                return 0
            
            logger.info("\n🗑️  Proceeding with force recreate...\n")
            success = create_collection(config, force_recreate=True)
            
            if success:
                logger.info("\n" + "=" * 70)
                logger.info("✅ Collection recreated successfully!")
                logger.info("=" * 70)
                
                # Show info
                info = get_collection_info(config)
                logger.info(f"Collection: {info['name']}")
                logger.info(f"Fields: {len(info['fields'])}")
                logger.info(f"Indexes: {len(info['indexes'])}")
                logger.info(f"Status: Ready for use")
                logger.info("=" * 70)
                return 0
            else:
                logger.error("\n❌ Failed to recreate collection")
                return 1
        
        # Default mode: Create if not exists
        logger.info("\n🚀 Creating collection schema...")
        logger.info("   (Safe mode - will NOT delete existing collections)\n")
        
        success = create_collection(config, force_recreate=False)
        
        if success:
            logger.info("\n" + "=" * 70)
            logger.info("✅ Schema setup successful!")
            logger.info("=" * 70)
            
            info = get_collection_info(config)
            logger.info(f"Collection: {info['name']}")
            logger.info(f"Fields: {len(info['fields'])}")
            logger.info(f"Indexes: {len(info['indexes'])}")
            logger.info(f"Status: Ready for use")
            logger.info("=" * 70)
            logger.info("\n💡 Next: Start your service with:")
            logger.info("   uvicorn main:app --reload --host 0.0.0.0 --port 8085")
            logger.info("=" * 70)
            return 0
        else:
            # Collection already exists
            logger.info("\n💡 To recreate with new schema, use:")
            logger.info("   python scripts/setup_milvus_schema.py --force")
            return 1
    
    except KeyboardInterrupt:
        logger.info("\n❌ Interrupted by user")
        return 130
    
    except Exception as e:
        logger.error(f"\n❌ Error: {e}", exc_info=True)
        return 1
    
    finally:
        # Disconnect
        try:
            connections.disconnect("default")
        except Exception:  # best-effort: cleanup disconnect, safe to ignore
            pass


if __name__ == "__main__":
    sys.exit(main())
